src/controllers/auth_controller.py
from flask import Blueprint, abort, jsonify, request, abort, redirect,url_for, flash, render_template
from flask_jwt_extended import create_access_token
from flask_login import current_user, login_user, logout_user, login_required
from schemas.UserSchema import user_schema, users_schema
from models.User import User
from main import db, login_manager
from forms import LoginForm, RegisterForm
from datetime import timedelta

auth = Blueprint("auth", __name__, url_prefix="/auth")

@auth.route("/register", methods=["POST"])
def register():
    user_fields = user_schema.load(request.json)

    user = User.query.filter_by(email=user_fields["email"]).first()

    #Check if the user has already existed in database
    if user:
        return abort(400, description="Email already registered")

    user = User()
    user.email = user_fields["email"]
    user.hash_password(user_fields["password"])

    db.session.add(user)
    db.session.commit()

    return jsonify(user_schema.dump(user)),201

@auth.route("/login", methods=["POST"])
def login():
    user_fields = user_schema.load(request.json)
    user = User.query.filter_by(email=user_fields["email"]).first()

    if user and user.check_password(user_fields["password"]):
        expiry = timedelta(days=1)
        access_token = create_access_token(identity=str(user.id), expires_delta=expiry)
        return jsonify({"token": access_token})
    else:
        return abort(401, description="Unauthorized")

# get all the user
@auth.route("/users", methods=["GET"])
def user_index():
    user = User.query.all()
    return jsonify(users_schema.dump(user))

@login_manager.user_loader
def load_user(user_id):
    """ Check if user is logged in on every page load """
    if user_id is not None:
        return User.query.get(user_id)
    return None

@login_manager.unauthorized_handler
def unauthorized():
    """ Redirect unauthorized users to Login page """
    flash("You must be logged in to view that page.")
    return redirect(url_for("auth.login_view"))

@auth.route("/register-view", methods=["GET", "POST"])
def register_view():
    """
    User registration page

    GET requests render registration page
    POST requests validate and user creation
    """
    form = RegisterForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # Check if user has already existed in the database
        if user:
            flash("Email already registered.")
        
        # New user creation
        user = User()
        user.email = form.email.data
        user.hash_password(form.password.data)
        
        db.session.add(user)
        db.session.commit()

        login_user(user)
        return redirect(url_for("profiles.create_view"))
    return render_template("register.html", form=form)   

@auth.route("/login-view", methods=["GET", "POST"])
def login_view():
    """
    Login page for registered user

    GET requests render login page
    POST requests validate and redirect user to dashboard
    """

    #Bypass if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for("profiles.profile_view",id=current_user.id))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        #Check if the password matched
        if user and user.check_password(form.password.data):
            login_user(user)
            next_page = request.args.get("next")
            return redirect(next_page or url_for(f"profiles.profile_view", id=current_user.id))
        flash("Invalid email and password.")
        return redirect(url_for("auth.login_view"))
    return render_template("login.html", form=form)

#logged the authenticated user out from the system
@auth.route("/logout", methods=["GET","POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login_view"))

src/controllers/jobs_controller.py
from main import db
from flask import Blueprint, jsonify, request, abort, render_template, flash, url_for, redirect
from flask_login import current_user, login_required
from flask_jwt_extended import jwt_required, get_jwt_identity
from forms import JobForm
from models.User import User
from models.Job import Job
from models.Profile import Profile
from models.JobType import JobType
from schemas.JobSchema import jobs_schema, job_schema
from sqlalchemy.orm import joinedload

jobs = Blueprint("jobs", __name__, url_prefix="/jobs")

@jobs.route("/", methods=["GET"])
@jwt_required()
def job_index():
    user_id = get_jwt_identity()
    user =  User.query.get(user_id)
    
    if user.is_admin == True:
        jobs = Job.query.options(joinedload("profiles")).all()
    else:
        profile = Profile.query.filter_by(user_id=user.id).first()
        jobs = Job.query.filter_by(profile_id=profile.id)
    return jsonify(jobs_schema.dump(jobs))

@jobs.route("/", methods=["POST"])
@jwt_required()
def job_create():
    user_id = get_jwt_identity()
    user = User.query.get(user_id)

    if not user:
        return abort(401, description="Invalid user")
    
    profile = Profile.query.filter_by(user_id=user.id).first()

    job_fields = job_schema.load(request.json)

    job_type = JobType.query.filter_by(name=job_fields["job_requested"]).first()

    if not job_type:
        return abort(404, description="Sorry, we do not have that service")

    new_job = Job()
    new_job.cust_name = job_fields["cust_name"]
    new_job.contact_num = job_fields["contact_num"]
    new_job.job_requested = job_fields["job_requested"]
    new_job.job_date = job_fields["job_date"]
    new_job.job_time = job_fields["job_time"]
    new_job.job_address = job_fields["job_address"]
    new_job.job_status = job_fields["job_status"]
    new_job.job_notes = job_fields["job_notes"]
    new_job.profile_id = profile.id
    job_type.jobs.append(new_job)
    
    db.session.commit()
    
    return jsonify(job_schema.dump(new_job)), 201

@jobs.route("/<int:id>", methods=["GET"])
@jwt_required()
def job(id):
    user_id = get_jwt_identity()
    user = User.query.get(user_id)
    
    if not user:
        return abort(401, description="Invalid user")
    
    profile = Profile.query.filter_by(user_id=user.id).first()

    if user.is_admin == False:
        if profile.jobs == []:
            return abort(400, description="There is no job(s) in your account")

        job = Job.query.filter_by(id=id, profile_id=profile.id)

        if job.count() != 1:
            return abort(401, description="Unauthorised to access this job information")
    else:
        job = Job.query.filter_by(id=id)
    return jsonify(job_schema.dump(job[0]))

@jobs.route("/<int:id>", methods=["PUT","PATCH"])
@jwt_required()
def job_update(id):
    user_id =get_jwt_identity()
    user = User.query.get(user_id)

    if not user:
        return abort(401, description="Invalid User")
    
    profile = Profile.query.filter_by(user_id=user.id).first()
    job_fields = job_schema.load(request.json)

    if user.is_admin == True:
        job = Job.query.filter_by(id=id)
    else:
        job = Job.query.filter_by(id=id, profile_id=profile.id)
        if job.count() != 1:
            return abort(401, description="Unauthorised to update this job details")
    
    job.update(job_fields)
    db.session.commit()

    return jsonify(job_schema.dump(job[0]))

@jobs.route("/<int:id>", methods=["DELETE"])
@jwt_required()
def job_delete(id):
    user_id = get_jwt_identity()
    user = User.query.get(user_id)

    if not user:
        return abort(401, description="Invalid user")

    if user.is_admin == True:
        job = Job.query.filter_by(id=id).first()
        if not job:
            return abort(404, description="Job is not existed in the system")
        db.session.delete(job)
        db.session.commit()
    else:
        return abort(401, description="Unauthorised user")
    return jsonify(job_schema.dump(job))

#get all the job by the logged in user and render index_job.html
@jobs.route("/job-view", methods=["GET","POST"])
@login_required
def index_view():
    user = User.query.get(current_user.id)
    profile = Profile.query.filter_by(user_id=user.id).first()
    jobs = Job.query.filter_by(profile_id=profile.id)

    return render_template("index_job.html", jobs=jobs)

#get all the job created in the system and render index_job.html
@jobs.route("/job-view/admin", methods=["GET","POST"])
@login_required
def admin_view():
    user = User.query.get(current_user.id)
    if user.is_admin == True:
        jobs = Job.query.options(joinedload("profiles")).all()
    else:
        flash("You need an admin access", category="info")
        return redirect(url_for("jobs.index_view"))
    return render_template("index_job.html", jobs=jobs)

#create new job
@jobs.route("/create-view", methods=["GET","POST"])
@login_required
def create_view():
    form = JobForm()
    
    if form.validate_on_submit():
        user = User.query.get(current_user.id)

        profile = Profile.query.filter_by(user_id=user.id).first()
        job_type = JobType.query.filter_by(id=form.job_requested.data).first()
        print(job_type.jobs)

        job = Job()
        job.cust_name = form.cust_name.data
        job.contact_num = form.contact_num.data
        job.job_requested = job_type.name
        job.job_date = form.job_date.data
        job.job_time = form.job_time.data
        
        keys = list(form.job_address.data)
        address = ", "
        values =[]
        for key in keys:
            value = form.job_address.data.get(key)
            values.append(str(value))
        job.job_address = address.join(values)

        job.job_notes = form.notes.data
        job.job_status = "Pending"
        profile.jobs.append(job)
        job_type.jobs.append(job)
        print(job_type.jobs)
        db.session.commit()

        flash("Your request is received!", category="success")
        return redirect(url_for("jobs.job_view", id=job.id))
    return render_template("create_job.html", form=form)

#Admin user able to check any job details in the system
#Customer user only able to access the job they created
@jobs.route("/job-view/<int:id>", methods=["GET"])
@login_required
def job_view(id):
    user_id = current_user.id
    user = User.query.get(user_id)

    if not user:
        flash("Invalid user", category="warnings")
        return redirect(url_for("auth.login_view"))   
    
    profile = Profile.query.filter_by(user_id=user.id).first()
    print(profile.jobs)
    if user.is_admin == True:
        job = Job.query.filter_by(id=id).first()
        print(job.id, job.cust_name)
    else:
        job = Job.query.filter_by(id=id, profile_id=profile.id).first()
        print(job.id, job.cust_name)

    if not job:
        flash("Unauthorised to access the job information", category="info")
        return redirect(url_for("jobs.index_view"))

    return render_template("job_page.html", job=job, profile=profile)

#Admin only able to update job status
#Customer able to update the details of their job request
@jobs.route("/update-view/<int:id>/<string:status>", methods=["GET","POST"])
@login_required
def update_view(id, status):
    user_id = current_user.id
    user = User.query.get(user_id)

    if not user:
        flash("Invalid user")
        return redirect(url_for("auth.login_view"))   
    
    profile = Profile.query.filter_by(user_id=user.id).first()

    if user.is_admin==True or status == "Cancelled":
        job = Job.query.filter_by(id=id)
        update_status = {"job_status":status}
        job.update(update_status)
        db.session.commit()
        flash(f"The job is {status}", category="info")
        return redirect(url_for("jobs.job_view", id=job.first().id))
    else:
        job = Job.query.filter_by(id=id, profile_id=profile.id)

    if job.count() != 1:
        flash("Unauthoried to update this job details", category="info")
        return redirect(url_for("jobs.index_view"))
    job_detail = job.first()

    # Prefill the form with the existing data
    form = JobForm(obj=job_detail)
    job_address = job_detail.job_address.split(", ")
    form.job_address.street_name.data = job_address[0]
    form.job_address.suburb.data = job_address[1]
    form.job_address.state.data = job_address[2]
    form.job_address.postcode.data = job_address[3]

    if form.validate_on_submit():
        # Getting new value
        job_type = JobType.query.filter_by(id=form.job_requested.data).first()

        keys = list(form.job_address.data)
        address = ", "
        values =[]
        for key in keys:
            value = form.job_address.data.get(key)
            values.append(str(value))

        job_fields = {
            "cust_name":form.cust_name.data,
            "contact_num":form.contact_num.data,
            "job_requested":job_type.name,
            "job_date":form.job_date.data,
            "job_time":form.job_time.data,
            "job_address":address.join(values),
            "job_notes":form.notes.data,
            "job_status":status,
            "profile_id":profile.id,
            "job_type_id":job_type.id
        }
        print(job)
        job.update(job_fields)
        print(job)
        db.session.commit()

        flash("Your data is updated!", category="success")
        return redirect(url_for("jobs.job_view", id=job_detail.id))
    return render_template("update_job.html", form=form, job=job_detail)

#Only admin allowed to delete the job from the system
@jobs.route("/delete-view/<int:id>", methods=["GET","POST"])
@login_required
def delete_view(id):
    user_id = current_user.id
    user = User.query.get(user_id)

    if not user:
        flash("Invalid user")
        return redirect(url_for("auth.login_view"))   
    
    if user.is_admin == True:
        job = job = Job.query.filter_by(id=id).first()
        if not job:

src/templates/create_job.html
{% extends "layout.html" %}

{% block content %}
  <div class="form-wrapper">

    <h1>Request a Service</h1>

    <form method="POST" action="{{url_for('jobs.create_view')}}">
      {{ form.csrf_token }}
      
      <div class="form-group">
        <label for="cust_name">Customer Name</label>
        {{form.cust_name(class_="form-control")}}
      </div>
      
      <div class="form-group">
        <label for="contact_num">Contact Number</label>
        {{form.contact_num(class_="form-control", type="tel", placeholder="04-1111 1111")}}
      </div>

      <div class="form-group">
        <label for="job_requested">Service Required</label>
        {{form.job_requested(class_="form-control")}}
      </div>

      <div class="form-group">
        <label for="job_date">Date</label>
        {{form.job_date(class_="form-control", type="date")}}
      </div>

      <div class="form-group">
        <label for="job_time">Time</label>
        {{form.job_time(class_="form-control", type="time")}}
      </div>

      <div class="form-group">
        <label for="job_address">Address</label><br>
        <div class="form-row">
          <div class="col-md-6 mb-3">
            <label for="street_name">Street Name</label>
            {{form.job_address.street_name(class_="form-control")}}
          </div>
        </div>
        <div class="form-row">
          <div class="col-md-3 mb-3">
            <label for="suburb">City / Suburb</label>
            {{form.job_address.suburb(class_="form-control")}}
          </div>
          <div class="col-md-3 mb-3">
            <label for="street_name">State</label>
            {{form.job_address.state(class_="form-control")}}
          </div>
          <div class="col-md-3 mb-3">
            <label for="street_name">Postcode</label>
            {{form.job_address.postcode(class_="form-control")}}
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="notes">Notes</label>
        {{form.notes(class_="form-control")}}
      </div>

      <div class="submit-button">
        <button type="submit" class="btn btn-primary"> Create </button>
      </div>      
    </form>
  </div>

{% endblock %}

src/templates/create_profile.html
{% extends "layout.html" %}

{% block content %}
  <div class="form-wrapper">

    <h1>Create Your Profile</h1>

    <form method="POST" action="{{url_for('profiles.create_view')}}">
      {{ form.csrf_token }}
      
      <div class="form-group">
        <label for="email">Username / Email address</label>
        <input type="email" class="form-control" name="email" placeholder="{{current_user.email}}" disabled>
      </div>
      
      <div class="form-group">
        <label for="firstname">First Name</label>
        <input type="text" class="form-control" name="firstname">
        {% if form.firstname.errors %}
          <ul class="errors">
            {% for error in form.firstname.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="lastname">Last Name</label>
        <input type="text" class="form-control" name="lastname">
        {% if form.lastname.errors %}
          <ul class="errors">
            {% for error in form.lastname.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="submit-button">
        <button type="submit"> Create </button>
      </div>      
    </form>
  </div>

{% endblock %}

src/templates/index_job.html
{% extends "layout.html" %}

{% block content %}
    {% for job in jobs %}
    <div class="card mb-3">
        <div class="card-header">
          {{job.job_date.strftime("%d %b %Y")}}, {{job.job_time.strftime("%H:%M")}} {{job.job_status}}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{job.cust_name}}</h5>
          <p class="card-text">Job Type : {{job.job_requested}}</p>
          <a href="{{url_for('jobs.job_view', id=job.id)}}" class="nav-link justify-content-end">Job Details</a>
        </div>
    </div>
    {% endfor %}
{% endblock %}

src/templates/job_page.html
{% extends "layout.html" %}

{% block content %}
    {% if current_user.is_admin == False %}
    <h1 style= "text-align: center;">Job {{profile.jobs.index(job) + 1}}</h1>
    {%else%}
    <h1 style= "text-align: center;">Job {{job.id}}</h1>
    {%endif%}
    <div class="col px-md-5"><div class="p-3 border bg-light">
        {% if current_user.is_admin == True %}
        <div class="content-section">
            <p class="card-text">Requested by: {{job.profiles.firstname}} {{job.profiles.lastname}}</p>
            <div class="card">
                <div class="card-header">
                    Customer Details
                </div>
                <div class="card-body">
                    <div class="text-secondary">Customer Number : {{job.cust_name}}</div>
                    <div class="text-secondary">Contact Number : {{job.contact_num}} </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Job Description
                </div>
                <div class="card-body">
                    <div class="text-secondary">{{job.job_requested}}</div>
                    <div class="text-secondary">Date : {{job.job_date.strftime("%d %b %Y")}}</div>
                    <div class="text-secondary">Time : {{job.job_time.strftime("%H:%M")}}</div>
                    <div class="text-secondary">Address : {{job.job_address}}</div>
                    <div class="text-secondary">Notes : {{job.notes}}</div>
                </div>
            </div>
            <div class="">
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('jobs.update_view', id=job.id, status="Scheduled")}}">Schedule</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{{url_for('jobs.delete_view', id=job.id)}}">Cancel</a>
            </div>
        {% else %}
        <div class="content-section">
            <p class="card-text">Requested by: {{job.profiles.firstname}} {{job.profiles.lastname}}</p>
            <div class="card">
                <div class="card-header">
                    Customer Details
                </div>
                <div class="card-body">
                    <div class="text-secondary">Customer Number : {{job.cust_name}}</div>
                    <div class="text-secondary">Contact Number : {{job.contact_num}} </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Job Description
                </div>
                <div class="card-body">
                    <div class="text-secondary">{{job.job_requested}}</div>
                    <div class="text-secondary">Date : {{job.job_date.strftime("%d %b %Y")}}</div>
                    <div class="text-secondary">Time : {{job.job_time.strftime("%H:%M")}}</div>
                    <div class="text-secondary">Address : {{job.job_address}}</div>
                    <div class="text-secondary">Notes : {{job.notes}}</div>
                </div>
            </div>
            <div class="">
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('jobs.update_view', id=job.id, status="Pending")}}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{{url_for('jobs.update_view', id=job.id, status="Cancelled")}}">Cancel</a>
            </div>
        {% endif %}    
        </div>
    </div>
{% endblock %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    
    {% if title %}:
      <title>{{title}}</title>
    {%else%}
      <title>Cleaning and Laundry Management System</title>
    {%endif%}
    
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href=#>Cleaning & Laundry</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          {% if current_user.is_authenticated %}
          <a class="nav-brand" href=#">Hi, {{current_user.profile[0]}}</a>
            <div class="navbar-nav mr-auto">
              
            </div>
          <!-- Navbar Right Side -->
            <div class="navbar-nav ">
              {% if current_user.is_admin == True %}
              <a href="{{url_for('jobs.admin_view')}}" class="nav-item nav-link">Requests</a>
              {%else%}
              <a href="{{url_for('jobs.create_view')}}" class="nav-item nav-link">New Requests</a>
              <a href="{{url_for('jobs.index_view')}}" class="nav-item nav-link">My Requests</a>
              {% endif %}
              <a href="{{url_for('profiles.profile_view',id=current_user.id)}}" class="nav-item nav-link">My Profile</a>
              <a href="{{url_for('auth.logout')}}" class="nav-item nav-link">Logout</a>           
            </div>
          {% else %}
            <div class="navbar-nav mr-auto"></div>
            <div class="navbar-nav">
              <a href="{{url_for('auth.login_view')}}" class="nav-item nav-link">Login</a>
              <a href="{{url_for('auth.register_view')}}" class="nav-item nav-link">Register</a>           
            </div>
          {% endif %} 
        </div>    
      </div>
    </nav>
  </header>
  <main role="main" class="container mr-auto">
    <div class="row">
      <div class="col">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock content %}
      </div>
    </div>  
  </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
</body>
</html>

src/templates/login.html
{% extends "layout.html" %}

{% block content %}
  <div class="form-wrapper">

    <h1>Log In</h1>

    <form method="POST" action="{{url_for('auth.login_view')}}">
      {{ form.csrf_token }}

      <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" name="email" placeholder="youremail@example.com">
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </div>
      
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password">
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="submit-button">
        {{ form.submit }}
      </div>

      <div class="login-register">
        <span>Don't have an account?</span>
        <a href="{{ url_for('auth.register_view') }}">Register.</a>
      </div>

    </form>
  </div>

{% endblock %}

src/templates/profile_page.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{profile.firstname}}'s Profile</h5>
                <div class="text-secondary">Full Name : {{profile.firstname}} {{profile.lastname}}</div>
                <div class="text-secondary">Email : {{profile.username}} </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/register.html
{% extends "layout.html" %}

{% block content %}
  <div class="form-wrapper">

    <h1>Register</h1>

    <form method="POST" action="{{url_for('auth.register_view')}}">
      {{ form.csrf_token }}

      <div class="form-group">
        <label for="email">Email address</label>
        <input type="text" class="form-control" name="email" placeholder=youremail@example.com>
        <!-- <small id="emailSample" class=form-text text-muted>Eg: youremail@example.com</small> -->
        
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password">
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
        </div>

      <div class="form-group">
        <label for="confirm_password">Confirm Password</label>
        <input type="password" class="form-control" name="confirm_password">
        {% if form.confirm_password.errors %}
          <ul class="errors">
            {% for error in form.confirm_password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
        </div>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>

    <div class="login-signup">
      <div>
        <span>Already have an account?</span>
        <a href="{{ url_for('auth.login_view') }}">Log in.</a>
      </div>
    </div>
  </div>

{% endblock %}

src/templates/update_job.html
{% extends "layout.html" %}

{% block content %}
  <div class="form-wrapper">

    <h1>Update Details</h1>
    <form method="POST" action="{{url_for('jobs.update_view', id=job.id, status="Pending")}}">
      {{ form.csrf_token }}
      <div class="form-group">
        <label for="cust_name">Customer Name</label>
        {{form.cust_name(class_="form-control")}}
      </div>
      
      <div class="form-group">
        <label for="contact_num">Contact Number</label>
        {{form.contact_num(class_="form-control", type="tel", placeholder="04-1234 5678")}}
      </div>

      <div class="form-group">
        <label for="job_requested">Service Required</label>
        {{form.job_requested(class_="form-control")}}
      </div>

      <div class="form-group">
        <label for="job_date">Date</label>
        {{form.job_date(class_="form-control", type="date")}}
      </div>

      <div class="form-group">
        <label for="job_time">Time</label>
        {{form.job_time(class_="form-control", type="time")}}
      </div>

      <div class="form-group">
        <label for="job_address">Address</label><br>
        <div class="form-row">
          <div class="col-md-6 mb-3">
            <label for="street_name">Street Name</label>
            {{form.job_address.street_name(class_="form-control")}}
          </div>
        </div>
        <div class="form-row">
          <div class="col-md-3 mb-3">
            <label for="suburb">City / Suburb</label>
            {{form.job_address.suburb(class_="form-control")}}
          </div>
          <div class="col-md-3 mb-3">
            <label for="street_name">State</label>
            {{form.job_address.state(class_="form-control")}}
          </div>
          <div class="col-md-3 mb-3">
            <label for="street_name">Postcode</label>
            {{form.job_address.postcode(class_="form-control")}}
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="notes">Notes</label>
        {{form.notes(class_="form-control")}}
      </div>

      <div class="submit-button">
        <button type="submit" class="btn btn-primary"> Update </button>
      </div>
    </form>
  </div>

{% endblock %}